trigger:
  branches:
    include:
      - main
  paths:
    include:
      - CloudServer/**

pool:
  name: "Default"

steps:
  - checkout: self
    persistCredentials: true

  - script: |
      git config --global user.email "bogdan.dumitrescu02@stud.acs.upb.ro"
      git config --global user.name "dumibxd26"

      mkdir temp-repo
      cd temp-repo
      git init
      git remote add azure https://$(AZURE_TOKEN)@dev.azure.com/bogdandumitrescu02/HouseSecuritySystemCloud/_git/HouseSecuritySystemCloud

      git fetch azure
      git checkout -b main
      git rm -rf . || true

      cp -r $(Build.SourcesDirectory)/CloudServer/* .

      git add .
      git commit -m "Keep only CloudServer directory"
      git push --force azure main
    env:
      AZURE_TOKEN: $(System.AccessToken)
    displayName: "Sync CloudServer Directory from GitHub to Azure DevOps"
