trigger:
  branches:
    include:
      - main
  paths:
    include:
      - CloudServer/**

pool:
  name: "Default"

steps:
  - checkout: self
    persistCredentials: true

  - script: |
      git config --global user.email "your-email@example.com"
      git config --global user.name "your-username"
      git remote add github https://$(GITHUB_TOKEN)@github.com/your-github-username/your-github-repo.git
      git remote add azure https://$(AZURE_TOKEN)@dev.azure.com/your-azure-org/your-azure-project/_git/your-azure-repo
      git fetch github
      git fetch azure
      git checkout main
      git reset --hard github/main
      git push --force azure main
    env:
      GITHUB_TOKEN: $(System.AccessToken)
      AZURE_TOKEN: $(System.AccessToken)
    displayName: "Sync GitHub to Azure DevOps"
