trigger:
  branches:
    include:
      - main
  paths:
    include:
      - CloudServer/**

pool:
  name: "Default"

steps:
  - checkout: self
    persistCredentials: true

  - script: |
      git config --global user.email "you@example.com"
      git config --global user.name "Your Name"
      git remote add azure https://bogdandumitrescu02@dev.azure.com/bogdandumitrescu02/HouseSecuritySystemCloud/_git/HouseSecuritySystemCloud
      git fetch azure
      git subtree push --prefix=CloudServer azure main
    displayName: "Sync CloudServer Directory to Azure DevOps"
