trigger:
  branches:
    include:
      - main
  paths:
    include:
      - CloudServer/**

pool:
  name: "Default"

steps:
  - checkout: self
    persistCredentials: true

  - script: |
      git config --global user.email "bogdan.dumitrescu02@stud.acs.upb.ro"
      git config --global user.name "dumibxd26"
      git remote remove azure || true
      git remote add azure https://$(System.AccessToken)@dev.azure.com/bogdandumitrescu02/HouseSecuritySystemCloud/_git/HouseSecuritySystemCloud
      git fetch azure
      git pull --rebase azure main
      git subtree push --prefix=CloudServer azure main
    env:
      GIT_ASKPASS: echo
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    displayName: "Sync CloudServer Directory to Azure DevOps"
